# fedora36 latex base image
#--------------------------------------------------------------------------
#
# docker_build_image   fedora:36      Dockerfile-fedora36-latex  base:fedora36-latex  "--no-cache"
# docker_run_image                                               base:fedora36-latex  [i]
# docker_tag_and_push_image                         maureeungaro/base:fedora36-latex
#
#--------------------------------------------------------------------------

FROM imagetemplate
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
RUN update-ca-trust








RUN dnf install -y \
	python3-devel \
    python3-scons \
	bzip2 wget curl nano git which bash tcsh zsh hostname gedit environment-modules \
	psmisc procps mailcap net-tools \
	perl-CPAN glibc-langpack-en \
    xorg-x11-server-Xvfb xterm \
    x11vnc novnc  \
    fluxbox supervisor \
    texlive-scheme-basic texlive-wrapfig texlive-multirow texlive-sidecap texlive-fancyhdr texlive-everysel \
    texlive-collection-fontsrecommended texlive-sauter texlive-revtex4 texlive-sttools \
    texlive-pythontex texlive-fvextra \
    && dnf -y update \
	&& dnf -y check-update \
	&& dnf clean packages \
	&& dnf clean all \
   	&& rm -rf /var/cache/yum


# Setup demo environment variables
ENV HOME=/root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1400 \
    DISPLAY_HEIGHT=1000 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes

COPY conf.d /app/conf.d
COPY supervisord.conf entrypoint.sh /app/



CMD ["/app/entrypoint.sh"]
EXPOSE 8080
