# ubuntu base image
#-----------------------------------------------------------------------------------------
#
# docker_build_image ubuntu:jammy  Dockerfile-ubuntu22  base:ubuntu22  "--no-cache"
# docker_run_image base:ubuntu22 [i]
# docker_tag_and_push_image base:ubuntu22
#
#-----------------------------------------------------------------------------------------

FROM imagetemplate
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

RUN    apt update \
	&& apt  autoclean



# no interactive session to identify the timezone
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && DEBIAN_FRONTEND=noninteractive apt  install -y --no-install-recommends tzdata \
	cmake make g++ \
    expat libexpat1-dev \
    libmysqlclient-dev \
	libpython3-dev scons \
	libglu1-mesa-dev   libx11-dev   libxpm-dev   libxft-dev   libxt-dev   libxmu-dev   libxrender-dev \
	bzip2 wget curl nano git bash tcsh zsh hostname gedit environment-modules \
	psmisc procps mailcap net-tools \
	libcpandb-perl \
    xvfb x11vnc novnc fluxbox xterm supervisor  \
    qtbase5-dev libqt5widgets5 libqt5opengl5-dev libqt5printsupport5 libsqlite3-dev \
	&& apt  autoclean


# root installed using tarball
ENV ROOT_RELEASE=6.28.04
ENV ROOT_FILE=root_v${ROOT_RELEASE}.Linux-ubuntu22-x86_64-gcc11.3.tar.gz
ENV ROOT_INSTALL_DIR=/usr/local

RUN cd ${ROOT_INSTALL_DIR} \
    && wget https://root.cern/download/${ROOT_FILE} \
    && tar -xzvf ${ROOT_FILE} \
    && rm ${ROOT_FILE} \
    && echo "cd ${ROOT_INSTALL_DIR}/root ; source bin/thisroot.sh ; cd -" >> /etc/profile.d/root.sh

# Setup demo environment variables
ENV HOME=/root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1400 \
    DISPLAY_HEIGHT=1000 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes

COPY conf.d /app/conf.d
COPY supervisord.conf entrypoint.sh /app/


CMD ["/app/entrypoint.sh"]
EXPOSE 8080