#
# docker centos8 base image
#--------------------------------------------------------------------------
#
# To manually build and push the container (use --no-cache to force rebuild):
#
#  docker build --progress=plain            -f Dockerfile-centos8 -t base:centos8 .
#  docker build --progress=plain --no-cache -f Dockerfile-centos8 -t base:centos8 .
#
#  docker tag base:centos8 jeffersonlab/base:centos8
#
#  docker push jeffersonlab/base:centos8
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm base:centos8 bash
#
#  docker run -it --rm jeffersonlab/base:centos8 bash
#
#--------------------------------------------------------------------------

FROM centos:centos8
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

# migrate from Centos Linux 8 to Centos Stream 8
RUN dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos

# See https://fedoraproject.org/wiki/EPEL
RUN yum install -y epel-release \
	&& yum -y install 'dnf-command(config-manager)' \
	&& yum -y install dnf-plugins-core \
	&& yum -y config-manager --set-enabled powertools \
	&& yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# notice: gcc-c++ is gcc8
# xrandr added so we could change resolutions
RUN yum install -y \
	cmake3 \
	make \
	gcc-c++ \
	mysql-devel \
	python3-devel \
	python3-scons \
	mesa-libGLU-devel \
	libX11-devel \
	libXpm-devel \
	libXft-devel \
	libXt-devel \
	libXmu-devel \
	libXrender-devel \
	expat-devel \
	bzip2 \
	qt5-qtbase-devel \
	qt5-linguist \
	wget \
	nano \
	git \
	which \
	tcsh \
	psmisc \
	procps \
	hostname \
	tigervnc-server \
	xfce4-session \
	xfce4-panel \
	xfce4-terminal \
	xfwm4 \
	mailcap \
	net-tools \
	glx-utils \
	xterm \
	nedit \
	perl-CPAN \
	glibc-langpack-en \
	xrandr \
	&& yum clean packages \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& ln -s /usr/bin/cmake3 /usr/local/bin/cmake \
	&& git clone https://github.com/novnc/noVNC /opt/noVNC \
	&& cd /opt/noVNC \
	&& ln -s vnc.html index.html \
	&& rm -rf .git* \
	&& mkdir -p /container/utilities \
	&& ln -s /usr/bin/scons-3 /usr/bin/scons 

# These define an alias and a script for easily starting up the
# servers from either bash or tcsh.
COPY scripts/xstart_alias.sh  /etc/profile.d
COPY scripts/xstart_alias.csh /etc/profile.d
COPY scripts/xstart.sh  /container/utilities
COPY scripts/xstart.csh /container/utilities
COPY scripts/xstop /usr/bin
ADD  dot_config /root/.config
