#
# docker base image for the final docker image
#
# This file is included by the script createDocker 
#
#--------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-centos7 -t gemc:centos7 .
#
#  docker tag gemc:centos7 jeffersonlab/gemc:centos7
#
#  docker push jeffersonlab/gemc:centos7
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm gemc:centos7 bash
#
#  docker run -it --rm jeffersonlab/gemc:centos7 bash
#
#--------------------------------------------------------------------------

### START BASEOS

FROM centos:7.5.1804
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

RUN yum install -y epel-release






RUN yum install -y \
	cmake3 \
	make \
	gcc-c++ \
	mysql-devel \
	python-devel \
	scons \
	libX11-devel \
	mesa-libGLU-devel \
	libXt-devel \
	libXmu-devel \
	libXrender-devel \
	libXpm-devel \
	libXft-devel \
	expat-devel \
	bzip2 \
	qt5-qtbase-devel \
	qt5-linguist \
	wget \
	nano \
	git \
	which \
	tcsh \
	psmisc \
	tigervnc-server \
	xfce4-session \
	xfce4-panel \
	xfce4-terminal \
	xfwm4 \
	mailcap \
	net-tools \
	glx-utils \
	xterm \
	nedit \
	git \
	python-websockify \
	ghostscript-fonts \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& git clone https://github.com/kanaka/noVNC.git /opt/noVNC \
	&& cd /opt/noVNC \
	&& ln -s vnc.html index.html \
	&& mkdir -p /container/utilities

# These define an alias and a script for easily starting up the
# servers from either bash or tcsh.
COPY scripts/xstart_alias.sh  /etc/profile.d
COPY scripts/xstart_alias.csh /etc/profile.d
COPY scripts/xstart.sh  /container/utilities
COPY scripts/xstart.csh /container/utilities
COPY scripts/xstop /usr/bin
ADD  dot_config /root/.config

### END BASEOS
