#
# docker fedora32 base image
#--------------------------------------------------------------------------
#
# To manually build and push the container (use --no-cache to force rebuild):
#
#  docker build --progress=plain            -f Dockerfile-fedora32 -t gemc:fedora32 .
#  docker build --progress=plain --no-cache -f Dockerfile-fedora32 -t gemc:fedora32 .
#
#  docker tag gemc:fedora32 jeffersonlab/gemc:fedora32
#
#  docker push jeffersonlab/gemc:fedora32
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm gemc:fedora32 bash
#
#  docker run -it --rm jeffersonlab/gemc:fedora32 bash
#
#--------------------------------------------------------------------------

FROM fedora:32
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

RUN yum -y update \
	&& yum -y check-update


# notice: gcc-c++ is gcc8
RUN yum install -y \
	cmake3 \
	make \
	gcc-c++ \
	mysql-devel \
	python3-devel \
	python3-scons \
	mesa-libGLU-devel \
	libX11-devel \
	libXpm-devel \
	libXft-devel \
	libXt-devel \
	libXmu-devel \
	libXrender-devel \
	expat-devel \
	bzip2 \
	qt5-qtbase-devel \
	qt5-linguist \
	wget \
	nano \
	git \
	which \
	tcsh \
	psmisc \
	tigervnc-server \
	xfce4-session \
	xfce4-panel \
	xfce4-terminal \
	xfwm4 \
	mailcap \
	net-tools \
	glx-utils \
	xterm \
	nedit \
	perl-CPAN \
	glibc-langpack-en \
	root \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& ln -s /usr/bin/cmake3 /usr/local/bin/cmake \
	&& git clone https://github.com/kanaka/noVNC.git /opt/noVNC \
	&& cd /opt/noVNC \
	&& ln -s vnc.html index.html \
	&& mkdir -p /container/utilities


# These define an alias and a script for easily starting up the
# servers from either bash or tcsh.
COPY scripts/xstart_alias.sh  /etc/profile.d
COPY scripts/xstart_alias.csh /etc/profile.d
COPY scripts/xstart.sh  /container/utilities
COPY scripts/xstart.csh /container/utilities
COPY scripts/xstop /usr/bin
ADD  dot_config /root/.config
