#
# docker 2.7 (jlab 2.3) libraries image
#
#--------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-2.7 -t gemc:2.7 .
#
#  docker tag gemc:2.7 jeffersonlab/gemc:2.7
#
#  docker push jeffersonlab/gemc:2.7
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm gemc:2.7 bash
#
#  docker run -it --rm jeffersonlab/gemc:2.7 bash
#
#--------------------------------------------------------------------------

FROM jeffersonlab/gemc:centos8
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ADD .jlab_software /root

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION 2.3

RUN mkdir -p $JLAB_ROOT/$JLAB_VERSION $JLAB_ROOT/work

WORKDIR $JLAB_ROOT

RUN rm -f ceInstall_$JLAB_VERSION.tar.gz \
	&& wget -c http://www.jlab.org/12gev_phys/packages/sources/ceInstall/ceInstall_$JLAB_VERSION.tar.gz \
	&& tar -zxpf ceInstall_$JLAB_VERSION.tar.gz --strip-components 1 -C $JLAB_VERSION \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_clhep \
	&& ./go_xercesc \
	&& ./go_qt \
	&& ./go_geant4 \
	&& ./go_sconsscript \
	&& ./go_evio \
	&& ./go_mysql \
	&& ./go_ccdb \
	&& ./go_mlibrary \
	&& ./go_gemc \
	&& rm -rf $JLAB_SOFTWARE/geant4/*/source \
	&& rm -rf $JLAB_SOFTWARE/xercesc/*/xerces-c-* \
	&& rm -rf $JLAB_SOFTWARE/mlibrary/*/cadmesh* \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh /etc/profile.d \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh /etc/profile.d 

WORKDIR $JLAB_ROOT/work
CMD bash /container/utilities/xstart.sh && sleep infinity
