# ubuntu base image
#-----------------------------------------------------------------------------------------
#
# docker_build_and_tag_image ubuntu:jammy  Dockerfile-ubuntu22  base:ubuntu22  "--no-cache"
# docker_run_image base:ubuntu22 [i]
# docker push jeffersonlab/base:ubuntu22
#
#-----------------------------------------------------------------------------------------

FROM imagetemplate
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

RUN    apt update \
	&& apt  autoclean


# no interactive session to identify the timezone
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime \
    && DEBIAN_FRONTEND=noninteractive apt  install -y --no-install-recommends tzdata \
	cmake make g++ \
    expat libexpat1-dev \
    libmysqlclient-dev \
	libpython3-dev scons \
	libglu1-mesa-dev   libx11-dev   libxpm-dev   libxft-dev   libxt-dev   libxmu-dev   libxrender-dev \
	bzip2 wget curl nano git bash tcsh zsh hostname gedit environment-modules \
	psmisc procps mailcap net-tools \
	libcpandb-perl \
    xvfb x11vnc novnc fluxbox xterm supervisor  \
    qtbase5-dev libsqlite3-dev \
	&& apt  autoclean


# root not available yet on ubuntu22, see https://root.cern/install/#conda
# so using conda for now. Notice 'ame' environment is used not sure how
ENV CONDA_INSTALLER_FILE Miniconda3-py310_23.3.1-0-Linux-aarch64.sh

RUN curl https://repo.anaconda.com/miniconda/$CONDA_INSTALLER_FILE -O \
    && bash $CONDA_INSTALLER_FILE -b \
    && source /root/miniconda3/etc/profile.d/conda.sh \
    && conda config --set channel_priority strict \
    && conda create -c conda-forge --name myroot root \
    && conda activate myroot


# Setup demo environment variables
ENV HOME=/root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1400 \
    DISPLAY_HEIGHT=1000 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes

COPY conf.d /app/conf.d
COPY supervisord.conf entrypoint.sh ubuntu_conda.sh /app/

RUN cat /app/ubuntu_conda.sh >> /root/.bashrc

CMD ["/app/entrypoint.sh"]
EXPOSE 8080