# Test based on https://github.com/theasp/docker-novnc
# docker build --progress=plain --no-cache -f Dockerfile-fluxbox-test -t base:test .
# docker run --rm -it -p 8080:8080 base:test
# browse to http://localhost:8080/vnc.html

#FROM debian:buster
FROM fedora:36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# Install git, supervisor, VNC, & X11 packages
RUN yum install -y \
      bash \
      fluxbox \
      git \
      net-tools \
      novnc \
      supervisor \
      x11vnc \
      xterm \
      xorg-x11-server-Xvfb

# Setup demo environment variables
ENV HOME=/root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1400 \
    DISPLAY_HEIGHT=1000 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes

COPY conf.d /app/conf.d
COPY supervisord.conf entrypoint.sh /app/

CMD ["/app/entrypoint.sh"]
EXPOSE 8080
