#
# docker centos8 base image
#--------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-centos8 -t gemc:centos8 .
#
#  docker tag gemc:centos8 jeffersonlab/gemc:centos8
#
#  docker push jeffersonlab/gemc:centos8
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm gemc:centos8 bash
#
#  docker run -it --rm jeffersonlab/gemc:centos8 bash
#
#--------------------------------------------------------------------------

FROM centos:centos8
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

# CentOS8 notes:
# See https://fedoraproject.org/wiki/EPEL
RUN yum install -y epel-release \
	&& yum install -y 'dnf-command(config-manager)' \
	&& yum -y config-manager --set-enabled PowerTools \
	&& yum -y update \
	&& yum -y check-update

RUN yum install -y \
	cmake3 \
	make \
	gcc-c++ \
	mysql-devel \
	python3-devel \
	python3-scons \
	libX11-devel \
	mesa-libGLU-devel \
	libXt-devel \
	libXmu-devel \
	libXrender-devel \
	libXpm-devel \
	libXft-devel \
	expat-devel \
	bzip2 \
	qt5-qtbase-devel \
	qt5-linguist \
	wget \
	nano \
	git \
	which \
	tcsh \
	psmisc \
	tigervnc-server \
	xfce4-session \
	xfce4-panel \
	xfce4-terminal \
	xfwm4 \
	mailcap \
	net-tools \
	glx-utils \
	xterm \
	nedit \
	git \
	perl-CPAN \
	 \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& ln -s /usr/bin/cmake3 /usr/local/bin/cmake \
	&& ln -s /usr/bin/scons-3 /usr/bin/scons \
	&& git clone https://github.com/kanaka/noVNC.git /opt/noVNC \
	&& cd /opt/noVNC \
	&& ln -s vnc.html index.html \
	&& mkdir -p /container/utilities


# These define an alias and a script for easily starting up the
# servers from either bash or tcsh.
COPY scripts/xstart_alias.sh  /etc/profile.d
COPY scripts/xstart_alias.csh /etc/profile.d
COPY scripts/xstart.sh  /container/utilities
COPY scripts/xstart.csh /container/utilities
COPY scripts/xstop /usr/bin
ADD  dot_config /root/.config
