# AlmaLinux image https://almalinux.org https://hub.docker.com/_/almalinux
#-----------------------------------------------------------------------------------------
#
# docker_build_image   almalinux:9    Dockerfile-alma9           base:almalinux9      "--no-cache"
# docker_run_image                                               base:almalinux9      [i]
# docker_tag_and_push_image                         jeffersonlab/base:almalinux9
#
#-----------------------------------------------------------------------------------------

FROM imagetemplate
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

ADD https://pki.jlab.org/JLabCA.crt /etc/pki/ca-trust/source/anchors/JLabCA.crt
RUN update-ca-trust

# alma specific:
# crb: for mysql-devel
# synergy: root, scons, vncs
RUN    dnf install -y  'dnf-command(config-manager)' \
    && dnf config-manager --set-enabled crb \
    && dnf install -y almalinux-release-synergy

RUN dnf install -y --allowerasing \
	git make cmake gcc-c++ \
	expat-devel \
	mysql-devel sqlite-devel \
	python3-devel \
    python3-scons \
	mesa-libGLU-devel libX11-devel libXpm-devel libXft-devel libXt-devel libXmu-devel libXrender-devel xrandr \
	bzip2 wget curl nano which bash tcsh zsh hostname gedit environment-modules \
	psmisc procps mailcap net-tools \
	perl-CPAN glibc-langpack-en \
    xorg-x11-server-Xvfb xterm \
    x11vnc novnc \
    # fluxbox supervisor
    qt5-qtbase-devel qt5-linguist \
    root \
    && dnf -y update \
	&& dnf -y check-update \
	&& dnf clean packages \
	&& dnf clean all \
	&& rm -rf /var/cache/yum \
	&& ln -s /usr/bin/cmake3 /usr/local/bin/cmake











# Setup demo environment variables
ENV HOME=/root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1400 \
    DISPLAY_HEIGHT=1000 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes

COPY conf.d /app/conf.d
COPY supervisord.conf entrypoint.sh /app/


CMD ["/app/entrypoint.sh"]
EXPOSE 8080