### START BASEOS

FROM centos:centos8
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

# Running the first line is not enough
RUN yum install -y epel-release \
	&& yum install -y 'dnf-command(config-manager)' \
	&& yum -y config-manager --set-enabled PowerTools \
	&& yum -y update \
	&& yum -y check-update

RUN yum install -y \
	cmake3 \
	make \
	gcc-c++ \
	mysql-devel \
	python3-devel \
	python3-scons \
	libX11-devel \
	mesa-libGLU-devel \
	libXt-devel \
	libXmu-devel \
	libXrender-devel \
	libXpm-devel \
	libXft-devel \
	expat-devel \
	bzip2 \
	qt5-qtbase-devel \
	qt5-linguist \
	wget \
	nano \
	git \
	which \
	tcsh \
	psmisc \
	tigervnc-server \
	xfce4-session \
	xfce4-panel \
	xfce4-terminal \
	xfwm4 \
	mailcap \
	net-tools \
	glx-utils \
	xterm \
	nedit \
	git \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& git clone https://github.com/kanaka/noVNC.git /opt/noVNC \
	&& cd /opt/noVNC \
	&& ln -s vnc.html index.html \
	&& mkdir -p /container/utilities



# These define an alias and a script for easily starting up the
# servers from either bash or tcsh.
COPY scripts/xstart_alias.sh  /etc/profile.d
COPY scripts/xstart_alias.csh /etc/profile.d
COPY scripts/xstart.sh  /container/utilities
COPY scripts/xstart.csh /container/utilities
COPY scripts/xstop /usr/bin
ADD  dot_config /root/.config

### END BASEOS
 
### START JLAB SOFTWARE

ADD .jlab_software /root

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION devel

RUN mkdir -p $JLAB_ROOT/$JLAB_VERSION $JLAB_ROOT/work

WORKDIR $JLAB_ROOT

RUN rm -f ceInstall_$JLAB_VERSION.tar.gz \
	&& wget -c http://www.jlab.org/12gev_phys/packages/sources/ceInstall/ceInstall_$JLAB_VERSION.tar.gz \
	&& tar -zxpf ceInstall_$JLAB_VERSION.tar.gz --strip-components 1 -C $JLAB_VERSION \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_clhep \
	&& ./go_xercesc \
	&& ./go_qt \
	&& ./go_geant4 \
	&& ./go_sconsscript \
	&& ./go_evio \
	&& ./go_mysql \
	&& ./go_ccdb \
	&& ./go_mlibrary \
	&& ./go_gemc \
	&& rm -rf $JLAB_SOFTWARE/geant4/*/source \
	&& rm -rf $JLAB_SOFTWARE/xercesc/*/xerces-c-* \
	&& rm -rf $JLAB_SOFTWARE/mlibrary/*/cadmesh* \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh /etc/profile.d \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh /etc/profile.d 

WORKDIR $JLAB_ROOT/work
CMD bash /container/utilities/xstart.sh && sleep infinity


### END JLAB SOFTWARE
 
