#
# gemc docker 2.9 (jlab 2.4) libraries image
#--------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-3.0 -t gemc:3.0 .
#
#  docker tag gemc:3.0 jeffersonlab/gemc:3.0
#
#  docker push jeffersonlab/gemc:3.0
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm gemc:3.0 bash
#
#  docker run -it --rm jeffersonlab/gemc:3.0 bash
#
#--------------------------------------------------------------------------

FROM jeffersonlab/gemc:centos8
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"


COPY .jlab_software /root

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION 2.5

RUN mkdir -p $JLAB_ROOT/$JLAB_VERSION $JLAB_ROOT/work

WORKDIR $JLAB_ROOT

# splitting commands for debugging purposes
RUN rm -rf ceInstall_$JLAB_VERSION.tar.gz $JLAB_ROOT/$JLAB_VERSION/* \
	&& wget -c http://www.jlab.org/12gev_phys/packages/sources/ceInstall/ceInstall_$JLAB_VERSION.tar.gz \
	&& tar -zxpf ceInstall_$JLAB_VERSION.tar.gz --strip-components 1 -C $JLAB_VERSION \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_clhep \
	&& ./go_xercesc \
	&& ./go_qt system \
	&& rm -rf $JLAB_SOFTWARE/xercesc/*/source \
	&& rm -rf $JLAB_SOFTWARE/xercesc/*/build \
	&& rm -rf $JLAB_SOFTWARE/xercesc/*/share

RUN source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
 	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_geant4 data \
	&& ./go_geant4 src \
	&& ./go_geant4 makeMT \
	&& rm -rf $JLAB_SOFTWARE/geant4/*/build \
	&& rm -rf $JLAB_SOFTWARE/geant4/*/source

RUN source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
 	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_sconsscript \
	&& ./go_glibrary \
	&& rm -rf $JLAB_SOFTWARE/glibrary/*/cadmesh* \

RUN source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
 	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_gemc 3.0 \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh /etc/profile.d \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh /etc/profile.d

WORKDIR $JLAB_ROOT/work
CMD bash /container/utilities/xstart.sh && sleep infinity
