# docker fedora36 base image - TODO: needs update to use fluxbox
#--------------------------------------------------------------------------
#
# To manually build and push the container (use --no-cache to force rebuild):
#
#  docker buildx build --platform linux/amd64  --progress=plain --no-cache -f Dockerfile-fedora36-latex -t base:fedora36-latex .
#  docker tag base:fedora36-latex maureeungaro/base:fedora36-latex
#  docker push maureeungaro/base:fedora36-latex
#
#  docker run -it --rm base:fedora36-latex bash
#
#--------------------------------------------------------------------------

FROM fedora:36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]


RUN   yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# xrandr added so we could change resolutions
RUN yum install -y \
	python3-devel python3-scons \
	bzip2 wget curl nano git which bash tcsh zsh hostname  gedit environment-modules \
	psmisc procps mailcap net-tools \
	perl-CPAN glibc-langpack-en \
    xorg-x11-server-Xvfb x11vnc novnc fluxbox xterm supervisor \
    texlive-scheme-basic \
    texlive-wrapfig \
    texlive-multirow \
    texlive-sidecap \
    texlive-fancyhdr \
    texlive-everysel \
    texlive-collection-fontsrecommended \
    texlive-sauter \
    texlive-revtex4 \
	&& yum clean packages \
	&& yum clean all \
	&& rm -rf /var/cache/yum




# Setup demo environment variables
ENV HOME=/root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1400 \
    DISPLAY_HEIGHT=1000 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes

COPY conf.d /app/conf.d
COPY supervisord.conf entrypoint.sh /app/



CMD ["/app/entrypoint.sh"]
EXPOSE 8080
