#
# docker fedora36 base image
#--------------------------------------------------------------------------
#
# To manually build and push the container (use --no-cache to force rebuild):
#
#  docker build --progress=auto            -f Dockerfile-fedora36 -t base:fedora36 .
#  docker build --progress=auto --no-cache -f Dockerfile-fedora36 -t base:fedora36 .
#
#  docker scan base:fedora36
#
#  docker tag base:fedora36 jeffersonlab/base:fedora36
#
#  docker push jeffersonlab/base:fedora36
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm base:fedora36 bash
#
#  docker run -it --rm jeffersonlab/base:fedora36 bash
#
#--------------------------------------------------------------------------

FROM fedora:36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

RUN   yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# xrandr added so we could change resolutions
# Notice: although this is identical to the previous CentoS8 image, it is not interactive. Why!!!
RUN yum install -y \
	cmake3 \
	make \
	gcc-c++ \
	gfortran \
	mysql-devel \
	python3-devel \
	python3-scons \
	mesa-libGLU-devel \
	libX11-devel \
	libXpm-devel \
	libXft-devel \
	libXt-devel \
	libXmu-devel \
	libXrender-devel \
	expat-devel \
	bzip2 \
	wget \
	nano \
	git \
	which \
	tcsh \
	zsh \
	psmisc \
	procps \
	hostname \
	tigervnc-server \
	xfce4-session \
	xfce4-panel \
	xfce4-terminal \
	xfwm4 \
	mailcap \
	net-tools \
	glx-utils \
	xterm \
	nedit \
	perl-CPAN \
	glibc-langpack-en \
	xrandr \
	environment-modules \
	&& yum clean packages \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& ln -s /usr/bin/cmake3 /usr/local/bin/cmake \
	&& git clone https://github.com/novnc/noVNC /opt/noVNC \
	&& cd /opt/noVNC \
	&& ln -s vnc.html index.html \
	&& rm -rf .git* \
	&& mkdir -p /container/utilities


# These define an alias and a script for easily starting up the
# servers from either bash or tcsh.
COPY scripts/xstart_alias.sh  /etc/profile.d
COPY scripts/xstart_alias.csh /etc/profile.d
COPY scripts/xstart.sh  /container/utilities
COPY scripts/xstart.csh /container/utilities
COPY scripts/xstop /usr/bin
ADD  dot_config /root/.config
