# gemc image - containing gemc2 or gemc3
# --------------------------------------------------------------------------
#
# docker_build_image base:fedora36  Dockerfile-cvmfs-base  cvmfs:fedora36  "--no-cache"
# docker_run_image cvmfs:fedora36 [i] [cvmf]
# docker_tag_and_push_image cvmfs:fedora36
#
#  docker tag cvmfs:fedora36 jeffersonlab/clas12software:production
#  docker tag cvmfs:fedora36 jeffersonlab/clas12software:devel
#
#  docker push jeffersonlab/clas12software:production
#  docker push jeffersonlab/clas12software:devel
#
# --------------------------------------------------------------------------

FROM imagetemplate
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

# flexiblas-devel added for mcgen support
# Added all root mandetary and optional dependencies from https://root.cern/install/dependencies/
# xrootd-client for xrootd
# lsof for tcsh modules

COPY gemc/bgMerginFilename.sh  /usr/bin/bgMerginFilename.sh
COPY localSetup-cvmfs.sh /app/localSetup.sh
RUN yum install -y \
	flexiblas-devel \
    liburing \
    xrootd-client lsof \
    git make cmake gcc-c++ gcc binutils \
    libX11-devel libXpm-devel libXft-devel libXext-devel python openssl-devel \
    redhat-lsb-core gcc-gfortran pcre-devel \
    mesa-libGL-devel mesa-libGLU-devel glew-devel ftgl-devel mysql-devel \
    fftw-devel cfitsio-devel graphviz-devel libuuid-devel \
    avahi-compat-libdns_sd-devel openldap-devel python3-numpy \
    libxml2-devel gsl-devel readline-devel qt5-qtwebengine-devel \
    R-devel R-Rcpp-devel R-RInside-devel

RUN  yum -y update \
    && yum -y check-update \
    && yum clean packages \
    && yum clean all