#
# docker fedora36 base image
#--------------------------------------------------------------------------
#
# To manually build and push the container (use --no-cache to force rebuild):
#
#  docker build --progress=plain            -f Dockerfile-fedora36 -t base:fedora36 .
#  docker build --progress=plain --no-cache -f Dockerfile-fedora36 -t base:fedora36 .
#
#  docker scan base:fedora36
#
#  docker tag base:fedora36 jeffersonlab/base:fedora36
#
#  docker push jeffersonlab/base:fedora36
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm              base:fedora36 bash
#  docker run -it --rm -p 8080:8080 base:fedora36
#
#  docker run -it --rm              jeffersonlab/base:fedora36 bash
#  docker run -it --rm -p 8080:8080 jeffersonlab/base:fedora36 bash
#
#--------------------------------------------------------------------------

FROM fedora:36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

RUN   yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# xrandr added so we could change resolutions
# removed: glx-utils - hardware acceleration hard to support (to be revised?)
RUN yum install -y \
	cmake3 \
	make \
	gcc-c++ \
	gfortran \
	mysql-devel \
	python3-devel \
	python3-scons \
	mesa-libGLU-devel \
	libX11-devel \
	libXpm-devel \
	libXft-devel \
	libXt-devel \
	libXmu-devel \
	libXrender-devel \
	expat-devel \
	bzip2 \
	wget \
	nano \
	git \
	which \
    bash \
	tcsh \
	zsh \
	psmisc \
	procps \
	hostname \
	mailcap \
	net-tools \
	xterm \
	nedit \
	perl-CPAN \
	glibc-langpack-en \
	xrandr \
	environment-modules \
    fluxbox \
    novnc \
    supervisor \
    x11vnc \
    xorg-x11-server-Xvfb \
	&& yum clean packages \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& ln -s /usr/bin/cmake3 /usr/local/bin/cmake


# Setup demo environment variables
ENV HOME=/root \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8 \
    DISPLAY=:0.0 \
    DISPLAY_WIDTH=1400 \
    DISPLAY_HEIGHT=1000 \
    RUN_XTERM=yes \
    RUN_FLUXBOX=yes

COPY conf.d /app/conf.d
COPY supervisord.conf entrypoint.sh /app/

CMD ["/app/entrypoint.sh"]
EXPOSE 8080