# docker devel (jlab devel) libraries image
#
#--------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-devel -t gemc:devel .
#
#  docker tag gemc:devel jeffersonlab/gemc:devel
#
#  docker push jeffersonlab/gemc:devel
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm gemc:devel bash
#
#  docker run -it --rm jeffersonlab/gemc:devel bash
#
#--------------------------------------------------------------------------

FROM jeffersonlab/gemc:centos8
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ADD .jlab_software /root

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION devel

RUN mkdir -p $JLAB_ROOT/$JLAB_VERSION $JLAB_ROOT/work

WORKDIR $JLAB_ROOT

RUN rm -f ceInstall_$JLAB_VERSION.tar.gz \
	&& wget -c http://www.jlab.org/12gev_phys/packages/sources/ceInstall/ceInstall_$JLAB_VERSION.tar.gz \
	&& tar -zxpf ceInstall_$JLAB_VERSION.tar.gz --strip-components 1 -C $JLAB_VERSION \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_clhep \
	&& ./go_xercesc \
	&& ./go_qt system\
	&& ./go_geant4 \
	&& ./go_sconsscript \
	&& ./go_evio \
	&& ./go_mysql \
	&& ./go_ccdb \
	&& ./go_mlibrary \
	&& ./go_gemc \
	&& rm -rf $JLAB_SOFTWARE/geant4/*/source \
	&& rm -rf $JLAB_SOFTWARE/xercesc/*/xerces-c-* \
	&& rm -rf $JLAB_SOFTWARE/mlibrary/*/cadmesh* \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh /etc/profile.d \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh /etc/profile.d 

WORKDIR $JLAB_ROOT/work
CMD bash /container/utilities/xstart.sh && sleep infinity
