#
# gemc docker 3.0 libraries image
# --------------------------------------------------------------------------
#
# To manually build and push the container (use --no-cache to force rebuild):
#
#  docker pull jeffersonlab/jlabce:2.6g3
#  docker build --progress=plain            -f Dockerfile-3.0 -t gemc:3.0 .
#  docker build --progress=plain --no-cache -f Dockerfile-3.0 -t gemc:3.0 .
#
#  docker tag gemc:3.0 jeffersonlab/gemc:3.0
#
#  docker push jeffersonlab/gemc:3.0
#
# --------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm -v ~/mywork:/jlab/work/mywork              gemc:3.0 sh
#
#  docker run -it --rm -v ~/mywork:/jlab/work/mywork jeffersonlab/gemc:3.0 sh
#
# --------------------------------------------------------------------------

FROM jeffersonlab/jlabce:2.6g3
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION 2.6

# remaking this copy so if these change we do not have to rebuild jlabce
# notice: they cannot `be sym links - can temp copy them here when needed
COPY jlab-g3.csh /root/jlab.csh
COPY jlab-g3.sh  /root/jlab.sh

WORKDIR $JLAB_ROOT

# ghostscript installed for eps to pdf conversion of dawn outputs
RUN yum install -y \
	ghostscript \
	&& yum clean packages \
	&& yum clean all \
	&& rm -rf /var/cache/yum

RUN cd $JLAB_ROOT/$JLAB_VERSION \
	&& ./go_reload $JLAB_VERSION \
	&& cp /root/jlab.* $JLAB_ROOT/$JLAB_VERSION/ce/

# scons build system
RUN cd $JLAB_ROOT/$JLAB_VERSION/install  \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& ./go_sconsscript \

# glibrary cadmesh
RUN source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
 	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_glibrary src  \
	&& ./go_glibrary cadmesh \
	&& ./go_glibrary make \
	&& rm -rf $JLAB_SOFTWARE/glibrary/*/build_log \
	&& rm -rf $JLAB_SOFTWARE/glibrary/*/cadmesh*

# gemc
RUN  cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& ./go_gemc 3.0

# dawn
RUN  cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& ./go_dawn


WORKDIR $JLAB_ROOT
CMD bash /container/utilities/xstart.sh && sleep infinity
