# Sim/gemc imagees, based on base:os
# --------------------------------------------------------------------------
#
# docker_build_sim_image        1.0 fedora36  /usr/local
# docker_run_sim_image          1.0 fedora36 [i]
# docker_tag_and_push_sim_image 1.0 fedora36
#
# /usr/local installation, for ci
# docker_build_gemc_image        4.4.2-5.4-5.5  fedora36  /usr/local
# docker_tag_and_push_gemc_image 4.4.2-5.4-5.5  fedora36
# docker_build_gemc_image        dev            fedora36  /usr/local
# docker_tag_and_push_gemc_image dev            fedora36
# docker_build_gemc_image        1.1            fedora36  /usr/local
# docker_build_gemc_image        2.11           fedora36  /usr/local
# docker_run_gemc_image          2.11           fedora36  [i]
# docker_tag_and_push_gemc_image 2.11           fedora36
#
# /cvmfs installation
# docker_build_sim_image         1.0           fedora36  /cvmfs/oasis.opensciencegrid.org/jlab/geant4
# docker_build_gemc_image        4.4.2-5.4-5.5 fedora36  /cvmfs/oasis.opensciencegrid.org/jlab/geant4
# docker_build_gemc_image        5.6-dev       fedora36  /cvmfs/oasis.opensciencegrid.org/jlab/geant4
# docker_run_gemc_image          4.4.2-5.4-5.5 fedora36-cvmfs  [i]
# docker_run_gemc_image          5.6-dev       fedora36-cvmfs  [i]
# --------------------------------------------------------------------------

FROM imagetemplate
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run bash shell instead of sh
SHELL ["/bin/bash", "-c"]

ARG SIM_OR_GEMC="na"
ARG VERSION="na"
ARG LOCAL_DIR_INSTALL="na"
ARG MODULE_TO_LOAD="na"

RUN echo "$SIM_OR_GEMC: VERSION=$VERSION, MODULE_TO_LOAD=$MODULE_TO_LOAD, LOCAL_DIR_INSTALL=$LOCAL_DIR_INSTALL"

ENV SIM_HOME $LOCAL_DIR_INSTALL
WORKDIR $SIM_HOME

COPY localSetup.sh $SIM_HOME
COPY install_gemc  $SIM_HOME

RUN sed  -i -e "s|templateSim|$SIM_HOME|g"   $SIM_HOME/localSetup.sh \
    && echo "module load $MODULE_TO_LOAD" >> $SIM_HOME/localSetup.sh \
    && cp $SIM_HOME/localSetup.sh /app/localSetup.sh \
    && cp $SIM_HOME/localSetup.sh /etc/profile.d/localSetup.sh

# gemc or sim installation
RUN source /app/localSetup.sh \
    && $SIM_HOME/install_gemc $SIM_OR_GEMC $VERSION $SIM_HOME \
    && strip --remove-section=.note.ABI-tag $QTDIR/lib/libQt5Core.so.5

