# sim image: geant4 base container
# --------------------------------------------------------------------------
#
# docker_build_sim_image        2.4 fedora36
# docker_run_sim_image          2.4 fedora36 [i]
# docker_tag_and_push_sim_image 2.4 fedora36
#
# --------------------------------------------------------------------------

FROM imagetemplate
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

ARG SIM_VERSION="na"

RUN echo "SIM_VERSION=$SIM_VERSION"

ENV SIM_HOME /usr/local
RUN mkdir -p $SIM_HOME /app
WORKDIR $SIM_HOME

COPY localSetup.sh $SIM_HOME/

RUN echo "module load sim/$SIM_VERSION" >> $SIM_HOME/localSetup.sh \
    && cp $SIM_HOME/localSetup.sh /app/localSetup.sh \
    && cp $SIM_HOME/localSetup.sh /etc/profile.d/localSetup.sh

# geant4 base install - sim
RUN git clone https://github.com/JeffersonLab/ceInstall \
    && source /app/localSetup.sh \
    && install_sim $SIM_VERSION \
    && strip --remove-section=.note.ABI-tag $QTDIR/lib/libQt5Core.so.5


