#
# gemc image - contains geant4 base container for gemc2 or gemc3
# the gemc version to sim version is taken care of in install_software
#
# --------------------------------------------------------------------------
#
#  docker pull jeffersonlab/base:fedora36
#  docker build --progress=plain --no-cache --build-arg GEMC_VERSION=2.10 -f Dockerfile-gemc-base -t gemc:baseg4 .
#  docker build --progress=plain --no-cache --build-arg GEMC_VERSION=1.0  -f Dockerfile-gemc-base -t gemc3:baseg4 .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm              gemc:baseg4 bash
#  docker run -it --rm -p 8080:8080 gemc:baseg4
#
#  docker run -it --rm              gemc3:baseg4 bash
#  docker run -it --rm -p 8080:8080 gemc3:baseg4
#
# --------------------------------------------------------------------------
#
#  docker tag gemc:2.10 jeffersonlab/gemc:baseg4
#  docker push jeffersonlab/gemc:baseg4
#
#  docker tag gemc3:1.0 jeffersonlab/gemc3:baseg4
#  docker push jeffersonlab/gemc3:baseg4
#
# --------------------------------------------------------------------------

FROM jeffersonlab/base:fedora36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"
ARG GEMC_VERSION="na"

RUN echo "GEMC_VERSION=$GEMC_VERSION"

RUN    yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# root added for banks / gstreamer plugins
# qt added for geant4 / gemc
RUN yum install -y \
	qt5-qtbase-devel \
	qt5-linguist \
    sqlite-devel \
    root

ENV SIM_HOME /usr/local
RUN mkdir -p $SIM_HOME /app
WORKDIR $SIM_HOME

# copy both files, decide which to keep below
COPY localSetupG2.sh localSetupG3.sh $SIM_HOME/

# if $GEMC_VERSION is 1.0 mv localSetupG3.sh otherwise mv localSetupG2.sh to /app
RUN if [ "$GEMC_VERSION" = "1.0" ] ; then \
    mv $SIM_HOME/localSetupG3.sh /app/localSetup.sh ; \
else  \
    mv $SIM_HOME/localSetupG2.sh /app/localSetup.sh ; \
fi

RUN rm -f  $SIM_HOME/localSetup* \
    && cp /app/localSetup.sh /etc/profile.d/localSetup.sh


COPY install_software $SIM_HOME

# geant4 base install
RUN git clone https://github.com/JeffersonLab/ceInstall \
    && source /app/localSetup.sh \
    && $SIM_HOME/install_software $GEMC_VERSION $SIM_HOME sim

