#
# gemc docker clas12 system for gemc 3.0
#
# --------------------------------------------------------------------------
#
#  docker pull effersonlab/gemc3:1.0
#  docker build --progress=plain --no-cache --build-arg CLAS12_SYSTEMS_VERSION=1.0  -f Dockerfile-c12s -t gemc3:1.0c12s .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm              gemc3:1.0c12s bash
#  docker run -it --rm -p 8080:8080 gemc3:1.0c12s
#
# --------------------------------------------------------------------------
#
#  docker tag gemc3:1.0c12s jeffersonlab/gemc3:1.0c12s
#  docker push              jeffersonlab/gemc3:1.0c12s
#
# --------------------------------------------------------------------------

FROM jeffersonlab/gemc3:1.0
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"
ARG CLAS12_SYSTEMS_VERSION="na"

# CLAS12TAG is needed to compare the geometry
ENV CLAS12TAG 5.1
ENV SIM_HOME /usr/local

RUN echo "CLAS12_SYSTEMS_VERSION=$CLAS12_SYSTEMS_VERSION"

COPY localSetupC12S.sh /app/localSetup.sh
COPY localSetupC12S.sh /etc/profile.d/localSetup.sh

# Java installation
RUN yum install -y \
	java-11-openjdk-devel \
	&& yum clean packages \
	&& yum clean all \
	&& rm -rf /var/cache/yum

# Groovy installation
# Warning: this does not work at JLAB due to certificate problems
# Adding --insecure did not work
RUN curl -s https://get.sdkman.io | bash \
	&& source "$HOME/.sdkman/bin/sdkman-init.sh" \
	&& sdk install groovy

## ensures ceInstall is at the latest version
RUN cd $SIM_HOME/ceInstall \
    && git pull \
    && source /app/localSetup.sh \
    && install_clas12_systems \
    && install_ccdb


# Getting
RUN cd $SIM_HOME \
    && mkdir -p clas12_tags/$CLAS12TAG \
    && cd clas12_tags \
    && wget https://github.com/gemc/clas12_tags/archive/refs/tags/$CLAS12TAG.tar.gz \
    && tar -xzf $CLAS12TAG.tar.gz --strip-components=1 -C $CLAS12TAG

# Run installClas12Coatjava.sh to install coatjava and build the geo and plugins
RUN cd $SIM_HOME/ceInstall \
    && source /app/localSetup.sh \
    && cd $CLAS12_SYSTEMS \
    && ./installClas12Coatjava.sh
