#
# cvmfs docker cvmfs base image - this relies on software installed on /cvmfs
#
#
# --------------------------------------------------------------------------
#
#  docker pull jeffersonlab/base:fedora36
#  docker build --progress=plain --no-cache -f Dockerfile-cvmfs -t gemc:cvmfs .
#
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm -v /cvmfs:/cvmfs              gemc:cvmfs bash
#  docker run -it --rm -v /cvmfs:/cvmfs -p 8080:8080 gemc:cvmfs
#
#
#
#
# --------------------------------------------------------------------------
#
#  docker tag gemc:cvmfs jeffersonlab/clas12software:production
#  docker tag gemc:cvmfs jeffersonlab/clas12software:devel
#
#  docker push jeffersonlab/clas12software:production
#  docker push jeffersonlab/clas12software:devel
#
# --------------------------------------------------------------------------

FROM jeffersonlab/base:fedora36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"




RUN    yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

ENV SIM_HOME /cvmfs/oasis.opensciencegrid.org/jlab/hallb/clas12/soft
WORKDIR $SIM_HOME

COPY localSetupC12cvmfs.sh /app/localSetup.sh
COPY localSetupC12cvmfs.sh /etc/profile.d/localSetup.sh

# flexiblas-devel added for mcgen support
# Added all root mandetary and optional dependencies from https://root.cern/install/dependencies/

RUN yum install -y \
	flexiblas-devel \
    liburing \
    git make cmake gcc-c++ gcc binutils \
    libX11-devel libXpm-devel libXft-devel libXext-devel python openssl-devel \
    redhat-lsb-core gcc-gfortran pcre-devel \
    mesa-libGL-devel mesa-libGLU-devel glew-devel ftgl-devel mysql-devel \
    fftw-devel cfitsio-devel graphviz-devel libuuid-devel \
    avahi-compat-libdns_sd-devel openldap-devel python3-numpy \
    libxml2-devel gsl-devel readline-devel qt5-qtwebengine-devel \
    R-devel R-Rcpp-devel R-RInside-devel