# gemc docker clas12 system for gemc 3.0
# --------------------------------------------------------------------------
#
# docker_build_c12s_image        1.1 5.1 fedora36
# docker_run_c12s_image          1.1 fedora36 [i]
# docker_tag_and_push_c12s_image 1.1 fedora36
#
# --------------------------------------------------------------------------

FROM imagetemplate
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

# run shell instead of sh
SHELL ["/bin/bash", "-c"]

ARG C12S_VERSION="na"
ARG C12T_VERSION="na"
RUN echo "C12S_VERSION=$C12S_VERSION, C12T_VERSION=$C12T_VERSION "

ENV SIM_HOME /usr/local

RUN javainstallationtemplate

RUN    echo "module load .c12s/$C12S_VERSION" >> $SIM_HOME/localSetup.sh \
    && echo "module load .ccdb"               >> $SIM_HOME/localSetup.sh \
    && cp $SIM_HOME/localSetup.sh /app/localSetup.sh \
    && cp $SIM_HOME/localSetup.sh /etc/profile.d/localSetup.sh

# Groovy installation
# Warning: this does not work at JLAB due to certificate problems
# Adding --insecure did not work
RUN curl -SL https://get.sdkman.io | bash \
	&& source "$HOME/.sdkman/bin/sdkman-init.sh" \
	&& sdk install groovy

## ensures ceInstall is at the latest version
RUN source /app/localSetup.sh \
    && cd $SIM_HOME/ceInstall \
    && git pull \
    && install_clas12_systems \
    && install_ccdb

# Getting clas12Tags
RUN cd $SIM_HOME \
    && mkdir -p clas12_tags/$C12T_VERSION \
    && cd clas12_tags \
    && curl -SL -O https://github.com/gemc/clas12_tags/archive/refs/tags/$C12T_VERSION.tar.gz \
    && tar -xzf $C12T_VERSION.tar.gz --strip-components=1 -C $C12T_VERSION \
    && rm -f $C12T_VERSION.tar.gz

# Run installClas12Coatjava.sh to install coatjava and build the geo and plugins
RUN source /app/localSetup.sh \
    && cd $CLAS12_SYSTEMS \
    && ./installClas12Coatjava.sh
