#
# gemc docker 3.0 libraries image
# --------------------------------------------------------------------------
#
# To manually build and push the container (use --no-cache to force rebuild):
#
#  docker pull jeffersonlab/jlabce:2.5g3
#  docker build --progress=plain            -f Dockerfile-3.0 -t gemc:3.0 .
#  docker build --progress=plain --no-cache -f Dockerfile-3.0 -t gemc:3.0 .
#
#  docker tag gemc:3.0 jeffersonlab/gemc:3.0
#
#  docker push jeffersonlab/gemc:3.0
#
# --------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm -v ~/mywork:/jlab/work/mywork              gemc:3.0 bash
#
#  docker run -it --rm -v ~/mywork:/jlab/work/mywork jeffersonlab/gemc:3.0 bash
#
# --------------------------------------------------------------------------

FROM jeffersonlab/jlabce:2.5g3
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION 2.5

WORKDIR $JLAB_ROOT

RUN cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& source /root/jlab-g3.sh \
	&& ./go_glibrary src  \
	&& ./go_glibrary cadmesh \
	&& ./go_glibrary make \
	&& rm -rf $JLAB_SOFTWARE/glibrary/*/build_log \
	&& rm -rf $JLAB_SOFTWARE/glibrary/*/cadmesh*

# remove API tag
RUN  cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& source /root/jlab-g3.sh \
	&& ./go_gemc 3.0 \
	&& ln -s /usr/bin/python3 /usr/bin/python \
	&& strip --remove-section=.note.ABI-tag /usr/lib64/libQt5Core.so.5


WORKDIR $JLAB_ROOT
CMD bash /container/utilities/xstart.sh && sleep infinity
