#
# jlabce image - containing gemc2 or gemc3
# the gemc version to sim version is taken care of in install_software
#
# --------------------------------------------------------------------------
#
#  docker pull jeffersonlab/base:fedora36
#  docker build --progress=plain --no-cache --build-arg GEMC_VERSION=2.10 -f Dockerfile-jlabce -t jlabce:2.5m .
#  docker build --progress=plain --no-cache --build-arg GEMC_VERSION=1.0  -f Dockerfile-jlabce -t gemc3:1.0 .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm              jlabce:2.5m bash
#  docker run -it --rm -p 8080:8080 jlabce:2.5m
#
#  docker run -it --rm              gemc3:1.0 bash
#  docker run -it --rm -p 8080:8080 gemc3:1.0
#
# --------------------------------------------------------------------------
#
#  docker tag jlabce:2.5m jeffersonlab/jlabce:2.5m
#  docker push jeffersonlab/jlabce:2.5m
#
#  docker tag gemc3:1.0 jeffersonlab/gemc3:1.0
#  docker push jeffersonlab/gemc3:1.0
#
# --------------------------------------------------------------------------

FROM jeffersonlab/base:fedora36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"
ARG GEMC_VERSION="na"

RUN echo "GEMC_VERSION=$GEMC_VERSION"

RUN    yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# root added for banks / gstreamer plugins
# qt added for geant4 / gemc
RUN yum install -y \
	qt5-qtbase-devel \
	qt5-linguist \
    root

ENV SIM_HOME /work
RUN mkdir -p $SIM_HOME /app
WORKDIR $SIM_HOME

# if $GEMC_VERSION is 1.0 copy gemc3 install_software
if [ "$GEMC_VERSION" = "1.0" ]; then
    COPY localSetupG3.sh /app/localSetup.sh
    COPY localSetupG3.sh /etc/profile.d/localSetup.sh
else
    COPY localSetupG2.sh /app/localSetup.sh
    COPY localSetupG2.sh /etc/profile.d/localSetup.sh
fi


COPY install_software $SIM_HOME


# sourcing localSetup.sh calls ceInstall/setup.sh confusing $0
# need to cd to /work/ceInstall
RUN git clone https://github.com/JeffersonLab/ceInstall \
    && source /app/localSetup.sh \
    && $SIM_HOME/install_software $GEMC_VERSION $SIM_HOME sim

RUN source /app/localSetup.sh \
    && $SIM_HOME/install_software $GEMC_VERSION $SIM_HOME  gemc
