#!/bin/zsh

source /usr/share/Modules/init/sh

# argument is gemc version, SIM_HOME
if [[ $# -eq 2 ]]; then
  gemc_version=$1
  export SIM_HOME=$2

  source $SIM_HOME/ceInstall/setup.sh install
  export TERM=${TERM:-xterm}

  if [[ $gemc_version == "2.11" ]]; then
    echo " > Installing gemc version $gemc_version - SIM_HOME is $SIM_HOME"
    $SIM_HOME/ceInstall/install/install_gemc  $gemc_version
  elif [[ $gemc_version == "1.1" ]]; then
    echo " > Installing gemc3 version $gemc_version - SIM_HOME is $SIM_HOME"
    $SIM_HOME/ceInstall/install/install_gemc3 $gemc_version
  else
    echo " > ERROR: gemc version $gemc_version is not supported. Exiting."
    exit 1
  fi

fi
