#!/bin/zsh

# the argument to this script are:
# 1. the gemc version to install
# 2. the SIM_HOME directory

# the gemc version could be:
# a. 2.X (gemc2)
# b. 1.X (gemc3)
# c. a dash separated list like 4.2-5.1-5.2 (clas12Tags).

source /usr/share/Modules/init/sh

# argument is gemc version, SIM_HOME
if [[ $# -eq 2 ]]; then
  gemc_version=$1
  export SIM_HOME=$2

  source $SIM_HOME/ceInstall/setup.sh install
  export TERM=${TERM:-xterm}

  if [[ $gemc_version == "2.11" ]]; then
    echo " > Installing gemc version $gemc_version - SIM_HOME is $SIM_HOME"
    $SIM_HOME/ceInstall/install/install_gemc  $gemc_version
  elif [[ $gemc_version == "1.1" || $gemc_version == "dev" ]]; then
    echo " > Installing gemc3 version $gemc_version - SIM_HOME is $SIM_HOME"
    $SIM_HOME/ceInstall/install/install_gemc3 $gemc_version
  elif [[ $gemc_version == *"-"* ]]; then
    # create array with  clas12Tags versions
    tags=(${(s/-/)gemc_version})
	  for g in $=tags
    do
	    echo " > Installing clas12Tag $g - SIM_HOME is $SIM_HOME"
	    install_gemc $g
    done
  else
    echo " > ERROR: gemc version $gemc_version is not supported. Exiting."
    exit 1
  fi

fi
