#
# docker image for CLAS12 Software Production Simulation - to be run in batch mode on OSG
#----------------------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-clas12software -t clas12software:2.0 .
#
#  docker tag clas12software:2.0 jeffersonlab/clas12software:2.0
#
#  docker push jeffersonlab/clas12software:2.0
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm clas12software:2.0 bash
#
#  docker run -it --rm jeffersonlab/clas12software:2.0 bash
#
#--------------------------------------------------------------------------

FROM jeffersonlab/clas12tags:g4.3.2

ENV JLAB_ROOT /jlab
ENV OSRELEASE Linux_CentOS7.5.1804-x86_64-gcc4.8.5
ENV JLAB_SOFTWARE /jlab/$JLAB_VERSION/$OSRELEASE
ENV JLAB_VERSION 2.3
ENV COATJTAG 6.5.3
ENV CLARATAG 4.3.12
ENV JAVADOWNLOAD jre-8u191-linux-x64.tar.gz
ENV CEDFILE ced.1.4.52.tar.gz
ENV WGETOPTONS -q --no-check-certificate


# For Nathan: I was using "clara and coatjava" section for the interactive container and "java and coatjava" for the OSG.
# For now I commented out the CLARA cause I know that builds the container fine.

# reconstruction: clara and coatjava. The wget options above would give error
# RUN export CLARA_HOME=$JLAB_ROOT/$JLAB_VERSION/claraHome \
# 	# creating log dir structure
# 	&& mkdir -p $CLARA_HOME/plugins/clas12/log /jlab/tmp \
# 	&& cd /jlab/tmp \
# 	&& wget https://claraweb.jlab.org/clara/_downloads/install-claracre-clas.sh \
# 	&& chmod u+x install-claracre-clas.sh \
# 	# new version of clara requires typing "Y" to remove old home dir
# 	&& echo Y | ./install-claracre-clas.sh -v $COATJTAG -f $CLARATAG


# java and coatjava
RUN cd $JLAB_SOFTWARE \
	# JAVA from Oracle
	# Get JRE tar.gz from https://www.oracle.com/technetwork/java/javase/downloads/index.html
	# The .tar.gz is then put at JLAB on /group/12gev_phys/www/packages/sources/java
	&& wget $WGETOPTONS https://www.jlab.org/12gev_phys/packages/sources/java/$JAVADOWNLOAD \
	&& tar -zxpvf $JAVADOWNLOAD \
	# reconstruction: coatjava. untar file in coatjava directory
	&& cd $JLAB_SOFTWARE/clas12 \
	&& wget $WGETOPTONS https://clasweb.jlab.org/clas12offline/distribution/coatjava/coatjava-$COATJTAG.tar.gz \
	&& mkdir -p coatjava ; tar -zxpvf coatjava-$COATJTAG.tar.gz  --strip-components 1 -C coatjava



# ced. The wget options above would give error
RUN cd /jlab/work \
	&& wget -q https://userweb.jlab.org/~heddle/ced/builds/$CEDFILE \
	&& tar -zxpvf $CEDFILE	 \
	&& mv cedbuild/ced.sh cedbuild/ced \
	&& chmod a+x cedbuild/ced\
	&& rm $CEDFILE


# ADD createClaraCook.csh $JLAB_SOFTWARE/clas12/bin/createClaraCook.csh

