#
# docker image for CLAS12 Production Simulation - to be run in batch mode on OSG
#-------------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-production -t gemc:production .
#
#  docker tag clas12tags:production jeffersonlab/clas12tags:production
#
#  docker push jeffersonlab/clas12tags:production
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm clas12tags:production bash
#
#  docker run -it --rm jeffersonlab/clas12tags:production bash
#
#--------------------------------------------------------------------------

FROM jeffersonlab/gemc:2.7
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ENV JLAB_ROOT /jlab
ENV OSRELEASE Linux_CentOS7.5.1804-x86_64-gcc4.8.5
ENV JLAB_SOFTWARE /jlab/$JLAB_VERSION/$OSRELEASE
ENV JLAB_VERSION 2.3
ENV CLAS12TAG 4.3.2
ENV CEDFILE ced.1.4.48.tar.gz
ENV CCDBSQLITE ccdb_2019-08-04.sqlite
ENV COATJTAG 6b.3.2
ENV JAVATAG 11.0.5
ENV JAVADOWNLOAD jdk-$JAVATAG"_linux-x64_bin.tar.gz"

# gfortran for clasdis generator
# root for genKYandOnePion and evio2root
# xemacs to help users
# libXtst for kpp-plots
# libfonts for kpp-plots fonts
RUN yum install -y gcc-gfortran xemacs libXtst libfonts root root-montecarlo-eg \
	&& yum clean all

WORKDIR $JLAB_ROOT

# Checking out clas12Tags and compiling CLAS12TAG
# Removing un-used tags and .git stuff
RUN git clone https://github.com/gemc/clas12Tags.git \
	&& cd $JLAB_ROOT/clas12Tags \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& rm -rf $JLAB_ROOT/$JLAB_VERSION/$OSRELEASE/gemc \
	&& ./goInstall $CLAS12TAG \
	# delete unecessary files
	&& rm -rf .git* `ls | grep -v goIns | grep -v $CLAS12TAG | grep -v env | grep -v REA | grep -v gcards`

# Getting the field maps
# Replacing the scripts in /etc and with the environment scripts
RUN mkdir -p /jlab/noarch/data \
	&& cd /jlab/noarch/data \
	&& wget -q http://clasweb.jlab.org/12gev/field_maps/TorusSymmetric.dat \
	&& wget -q http://clasweb.jlab.org/12gev/field_maps/clas12NewSolenoidFieldMap.dat \
	&& rm /etc/profile.d/jlab.csh \
	&& rm /etc/profile.d/jlab.sh

# java and coatjava
RUN   mkdir -p $JLAB_SOFTWARE/clas12/lib \
	&& mkdir -p $JLAB_SOFTWARE/clas12/bin \
	&& mkdir -p $JLAB_SOFTWARE/clas12/inc \
	&& cd $JLAB_SOFTWARE \
	# JAVA from Oracle
	# Get JRE tar.gz from https://www.oracle.com/technetwork/java/javase/downloads/index.html
	# The .tar.gz is then put at JLAB on /group/12gev_phys/www/packages/sources/java
	&& wget -q --no-check-certificate https://www.jlab.org/12gev_phys/packages/sources/java/$JAVADOWNLOAD \
	&& tar -zxpvf $JAVADOWNLOAD \
	# reconstruction: coatjava. untar file in coatjava directory
	&& cd $JLAB_SOFTWARE/clas12 \
	&& wget -q --no-check-certificate https://clasweb.jlab.org/clas12offline/distribution/coatjava/coatjava-$COATJTAG.tar.gz \
	&& mkdir -p coatjava ; tar -zxpvf coatjava-$COATJTAG.tar.gz  --strip-components 1 -C coatjava


# CCDBSQLITE
RUN cd /jlab/work \
	&& wget -q --no-check-certificate https://www.jlab.org/12gev_phys/packages/ccdb/$CCDBSQLITE

# Generators from clas12-mcgen
RUN cd /jlab/work \
	&& git clone --recurse-submodules https://github.com/JeffersonLab/clas12-mcgen.git \
	&& cd clas12-mcgen \
	&& rm -rf .git* */.git* \
	&& make \
	&& cp clasdis-nocernlib/clasdis      $JLAB_SOFTWARE/clas12/bin \
	&& cp inclusive-dis-rad/generate-dis $JLAB_SOFTWARE/clas12/bin \
	&& cp dvcsgen/dvcsgen                $JLAB_SOFTWARE/clas12/bin \
	&& cp genKYandOnePion/eg_ky          $JLAB_SOFTWARE/clas12/bin

# ced
RUN cd /jlab/work \
	&& wget -q https://userweb.jlab.org/~heddle/ced/builds/$CEDFILE	 \
	&& tar -zxpvf $CEDFILE	 \
	&& rm $CEDFILE

ADD environment/environment-$CLAS12TAG".csh"  /etc/profile.d
ADD environment/environment-$CLAS12TAG".sh"   /etc/profile.d
WORKDIR $JLAB_ROOT/work

# Temp /condor for el6 binding
RUN mkdir /condor \
	&& mkdir /etc/condor
