FROM jeffersonlab/gemc:2.7
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ENV JLAB_ROOT /jlab
WORKDIR $JLAB_ROOT

RUN yum install -y libXtst  \
	&& yum clean all

ADD tests/test1.sh /jlab
ADD tests/test2.sh /jlab
