#
# jlabce docker devel (jlab devel) libraries image
#--------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-devel-mt -t jlabce:devel-mt .
#
#  docker tag jlabce:devel-mt jeffersonlab/jlabce:devel-mt
#
#  docker push jeffersonlab/jlabce:devel-mt
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm jlabce:devel-mt bash
#
#  docker run -it --rm jeffersonlab/jlabce:devel-mt bash
#
#--------------------------------------------------------------------------

FROM jeffersonlab/gemc:devel-mt
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ADD .jlab_software /root

ENV ROOTV 6.20.04

# Root by itself, it's quite big package
RUN cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& ./go_root \
	&& rm -rf /jlab/devel/Linux_CentOS8.1.1911-x86_64-gcc8/root/root-$ROOTV"*"

RUN cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& ./go_banks 
#	&& ./go_jana

WORKDIR $JLAB_ROOT/work
CMD bash /container/utilities/xstart.sh && sleep infinity
