#
# jlabce docker devel (jlab devel) libraries image
#--------------------------------------------------------------------------
#
# To manually build and push the container:
#
#  docker build -f Dockerfile-devel -t jlabce:devel .
#
#  docker tag jlabce:devel jeffersonlab/jlabce:devel
#
#  docker push jeffersonlab/jlabce:devel
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm jlabce:devel bash
#
#  docker run -it --rm jeffersonlab/jlabce:devel bash
#
#--------------------------------------------------------------------------

FROM jeffersonlab/gemc:devel
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ADD .jlab_software /root

# Root by itself, it's quite big package
RUN cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& ./go_root

RUN cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& ./go_banks 
#	&& ./go_jana

WORKDIR $JLAB_ROOT/work
CMD bash /container/utilities/xstart.sh && sleep infinity
