#
# cvmfs docker cvmfs clas12Tags build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-clas12Tags -t cvmfs:clas12Tags .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:c12bfield bash
#  docker run -it --rm cvmfs:clas12Tags bash
#
# --------------------------------------------------------------------------

FROM cvmfs:c12bfield
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ENV CTAGS 5.1

# 5.1 won't compile with g4 10.6 unless the g4ptl is removed from
# $JLAB_ROOT/noarch/scons_bm/1.10/loadgeant4.py

RUN source /root/ce/jlab.sh \
	&& echo removing ptl and g4tasking, this step is only necessary for geant4 10.6 \
	&& sed -i s/validg4libs.append\(\'G4ptl\'\)//     $JLAB_ROOT/noarch/scons_bm/1.10/loadgeant4.py \
	&& sed -i s/validg4libs.append\(\'G4ptl.0\'\)//   $JLAB_ROOT/noarch/scons_bm/1.10/loadgeant4.py \
	&& sed -i s/validg4libs.append\(\'G4tasking\'\)// $JLAB_ROOT/noarch/scons_bm/1.10/loadgeant4.py \
	&& sed -i s/validg4libs.append\(\'G4ptl\'\)//     $JLAB_ROOT/noarch/scons_bm/1.10/loadgeant4.py \
	&& sed -i s/validg4libs.append\(\'G4ptl.0\'\)//   $JLAB_ROOT/noarch/scons_bm/1.10/loadgeant4.py \
	&& sed -i s/validg4libs.append\(\'G4tasking\'\)// $JLAB_ROOT/noarch/scons_bm/1.10/loadgeant4.py


# temp C12BFIELDS env

RUN source /root/ce/jlab.sh \
	&& cd $JLAB_SOFTWARE \
	&& export C12BFIELDS=$JLAB_SOFTWARE/cmag/1.1 \
	&& git clone https://github.com/gemc/clas12Tags.git \
	&& cd clas12Tags \
	&& sh -x \
	&& for gt in $CTAGS ;  \
		do \
			echo  ; \
			echo Compiling "$gt" ; \
			echo  ; \
			./goInstall "$gt" ; \
		done \
	&& echo done

# for 4.4.2 can do this manually in the cvmfs:mlibrary container:
# cd 2.4/install/
# export EVIO_VERSION=5.1
# export EVIO=$JLAB_SOFTWARE/evio/$EVIO_VERSION
# ./go_evio
# cd $JLAB_ROOT/clas12Tags
# goInstall 4.4.2
