#
# cvmfs docker cvmfs geant4 build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-geant4 -t cvmfs:geant4 .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:qt     bash
#  docker run -it --rm cvmfs:geant4 bash
#
# --------------------------------------------------------------------------

FROM cvmfs:qt
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

RUN source /root/ce/jlab.sh \
	&& cd /root/install \
	&& ./go_geant4  \
	&& rm -rf $JLAB_SOFTWARE/geant4/*/build* \
	&& rm -rf $JLAB_SOFTWARE/geant4/*/source

