#
# cvmfs docker cvmfs c12bfield build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-c12bfield -t cvmfs:c12bfield .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:mlibrary bash
#  docker run -it --rm cvmfs:c12bfield bash
#
# --------------------------------------------------------------------------

FROM cvmfs:mlibrary
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

ENV cmagTag 1.1

RUN source /root/ce/jlab.sh \
	&& cd /root/install \
	&& cd $JLAB_SOFTWARE \
	&& mkdir -p cmag/$cmagTag \
	&& cd cmag \
	&& git clone https://github.com/JeffersonLab/clas12-cmag $cmagTag \
	&& cd $cmagTag/src \
	&& make -j4 \

