#
# cvmfs docker cvmfs qt build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-qt -t cvmfs:qt .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:xercesc bash
#  docker run -it --rm cvmfs:qt      bash
#
# --------------------------------------------------------------------------

FROM cvmfs:xercesc
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

# notice 1: the go_qt should be modified to copy not link the qt libraries
# notice 2: the last line is due to a mistake in go_qt and can be removed when it will be fixed

RUN source /root/ce/jlab.sh \
	&& cd /root/install \
	&& sed -i 's/set system = ""/set system = "Linux"/' go_qt \
    && sed -i 's/ln -sfn/cp -r/' go_qt \
	&& ./go_qt system \
	&& strip --remove-section=.note.ABI-tag /usr/lib64/libQt5Core.so.5 \
    && rm -rf $QTDIR/lib/lib64

