#
# cvmfs docker cvmfs-build base image
# the gemc versions are dash-separated (if multiple)
# the gemc version to sim version is taken care of in install_software
# --------------------------------------------------------------------------
#
#  docker pull jeffersonlab/base:fedora36
#  docker build --progress=plain --no-cache --build-arg GEMC_VERSION=4.4.2-5.1 -f Dockerfile-cvmfs-build -t cvmfs:cvmfs-build .
#
#
# --------------------------------------------------------------------------
#
#  docker scan cvmfs:cvmfs-build
#
#
#
#
#
#
#
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:cvmfs-build bash
#
#
# --------------------------------------------------------------------------

FROM jeffersonlab/base:fedora36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"
ARG GEMC_VERSION="na"

RUN echo "GEMC_VERSIONs=$GEMC_VERSION"

RUN    yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# qt added for geant4 / gemc

RUN yum install -y \
	qt5-qtbase-devel \
	qt5-linguist


ENV SIM_HOME /cvmfs/oasis.opensciencegrid.org/jlab/hallb/clas12/soft
RUN mkdir -p $SIM_HOME
WORKDIR $SIM_HOME

COPY install_software $SIM_HOME

RUN git clone https://github.com/JeffersonLab/ceInstall \
    && $SIM_HOME/install_software $GEMC_VERSION $SIM_HOME sim

RUN $SIM_HOME/install_software $GEMC_VERSION $SIM_HOME ctag
