#
# cvmfs docker cvmfs-build base image
# --------------------------------------------------------------------------
#
#  docker pull jeffersonlab/base:fedora36
#  docker build --progress=plain --no-cache --build-arg PHYS_VERSION=2.4 -f Dockerfile-cvmfs-build -t cvmfs-build:cvmfs-build-2.4 .
#  docker build --progress=plain --no-cache --build-arg PHYS_VERSION=2.5 -f Dockerfile-cvmfs-build -t cvmfs-build:cvmfs-build-2.5 .
#  docker build --progress=plain --no-cache --build-arg PHYS_VERSION=2.6 -f Dockerfile-cvmfs-build -t cvmfs-build:cvmfs-build-2.6 .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs-build:cvmfs-build-2.4 bash
#  docker run -it --rm -v /cvmfs:/cvmfs  cvmfs-build:cvmfs-build-2.4 bash
#
# --------------------------------------------------------------------------

FROM base:fedora36
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"
ARG PHYS_VERSION="na"


RUN   yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# xrandr added so we could change resolutions
RUN yum install -y \
	qt5-qtbase-devel \
	qt5-linguist

WORKDIR /work

COPY install_software $WORKDIR/install_software

ENV PHYS_HOME /cvmfs/oasis.opensciencegrid.org/jlab/hallb/clas12/soft
RUN mkdir -p $PHYS_HOME

RUN git clone http://github.com/JeffersonLab/ceInstall \
    && $WORKDIR/install_software $PHYS_VERSION
