#
# cvmfs docker cvmfs base image
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-cvmfs -t cvmfs:cvmfs .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:cvmfs bash
#  docker run -it --rm -v /cvmfs:/cvmfs  cvmfs:cvmfs bash
#
# --------------------------------------------------------------------------
#
#  docker tag cvmfs:cvmfs jeffersonlab/clas12software:production
#  docker tag cvmfs:cvmfs jeffersonlab/clas12software:devel
#
#  docker push jeffersonlab/clas12software:production
#  docker push jeffersonlab/clas12software:devel
#
# --------------------------------------------------------------------------

FROM base:fedora36
LABEL maintainer="Maurizio Ungaro <ungaro@jlab.org>"

RUN   yum -y update \
	&& yum -y check-update \
	&& yum clean packages \
	&& yum clean all

# flexiblas-devel added for mcgen support
# Notice: although this is identical to the previous CentoS8 image, it is not interactive. Why!!!
RUN yum install -y \
	flexiblas-devel \
    liburing