#
# cvmfs docker cvmfs clhep build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-clhep -t cvmfs:clhep .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:2.4   bash
#  docker run -it --rm cvmfs:clhep bash
#
# --------------------------------------------------------------------------

FROM cvmfs:2.4
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

RUN source /root/ce/jlab.sh \
	&& cd /root/install \
	&& ./go_clhep \
	&& rm -rf $JLAB_SOFTWARE/clhep/*/build*
