#
# cvmfs docker cvmfs evio build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-evio -t cvmfs:evio .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:ccdb bash
#  docker run -it --rm cvmfs:evio bash
#
# --------------------------------------------------------------------------

FROM cvmfs:ccdb
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"


RUN source /root/ce/jlab.sh \
	&& cd /root/install \
	&& export EVIO_VERSION=5.1 \
	&& export EVIO=$JLAB_SOFTWARE/evio/$EVIO_VERSION \
	&& ./go_evio \
	&& rm -rf $JLAB_SOFTWARE/evio/*.gz

