#
# cvmfs docker cvmfs hipo build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-hipo -t cvmfs:hipo .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:evio bash
#  docker run -it --rm cvmfs:hipo bash
#
# --------------------------------------------------------------------------

FROM cvmfs:evio
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

RUN yum install -y lz4-devel\
	&& yum clean packages \
	&& yum clean all

RUN source /root/ce/jlab.sh \
	&& cd /root/install \
	&& ./go_hipo \
	&& rm -rf $JLAB_SOFTWARE/hipo/*.gz

