#
# cvmfs docker cvmfs ccdb build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-ccdb -t cvmfs:ccdb .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:scons bash
#  docker run -it --rm cvmfs:ccdb bash
#
# --------------------------------------------------------------------------

FROM cvmfs:scons
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

RUN source /root/ce/jlab.sh \
	&& cd /root/install \
	&& ./go_ccdb  \
	&& rm -rf $JLAB_SOFTWARE/ccdb/*/tmp \
	&& rm -rf $JLAB_SOFTWARE/ccdb/*/java \
	&& rm -rf $JLAB_SOFTWARE/ccdb/*/doc \
	&& rm -rf $JLAB_SOFTWARE/ccdb/*/swig \

