#
# cvmfs docker cvmfs scons build
# --------------------------------------------------------------------------
#
#  docker build --progress=plain --no-cache -f Dockerfile-scons -t cvmfs:scons .
#
# --------------------------------------------------------------------------
#
#  docker run -it --rm cvmfs:geant4 bash
#  docker run -it --rm cvmfs:scons bash
#
# --------------------------------------------------------------------------

FROM cvmfs:geant4
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"


RUN source /root/ce/jlab.sh \
	&& cd /root/install \
	&& ./go_sconsscript
