#!/bin/zsh -i

export SIM_HOME=/cvmfs/oasis.opensciencegrid.org/jlab/hallb/clas12/soft

. $SIM_HOME/ceInstall/modules/setup.sh

export TERM=${TERM:-xterm}

# parse argument. If no argument given, set version to all available
# module test may be different in modules/5.0 so here we are installing packages
# one by one
if [[ $# -eq 2 ]]; then
 	echo " > Installing $2 for version $1 "

 	if [[ $2 == "geant4" ]]; then
 		install_sim $1
 	elif [[ $2 == "clas12" ]]; then
		install_gemc $1
 	fi

fi

